### PR TITLE
Use Go Module

### PR DESCRIPTION
**Pull request by supl**
This PR initiates Go module `github.com/scalar-labs/cassy/entrypoint` to take advantage of Go Module.
In short, we don't have to specify `$GOPATH` anymore to lookup the dependencies.

### CODE REVIEW

**Comment by feeblefakie** [comment]
@supl This is very nice ! I wanted to do this but couldn't do it due to lack of experience in go module.

**Comment by supl** [comment]
Yes.
The Golang community mentions that Go module is production-ready since Go 1.14.
I would recommend using it for dependency management.

**Comment by feeblefakie** [comment]
@supl Is it ready for review ?

**Comment by supl** [comment]
@feeblefakie
Yes. Please.
I think we don't need to change the document.
The build command remains in `go build`.

**Pull request merged**
